### ISSUE TITLE
CI/CD

### ISSUE THREAD

**Issue by herpiko** [BlankOn/irgsh-go#2]

**Comment by tuanpembual** [comment]
So how we will start?
I still blank about our plan.

**Comment by herpiko** [comment]
@tuanpembual 

The CI part was done. https://github.com/BlankOn/irgsh-go/actions/runs/322486606

CD job(s):

- Deploy
  - on:
    - commit to master
  - tasks:
    - Send it to rani.boi
    - Turn of the services
    - Replace the binaries
    - Turn on the services

Use scp and ssh, set the newly generated SSH key in secrets settings.

**Comment by herpiko** [comment]
Also change [the build command](https://github.com/BlankOn/irgsh-go/blob/master/.github/workflows/main.yml) to `make release`. It will pack the binaries, config, templates etc to `target/release.tar.gz`. This `release.tar.gz` should be the artifact.

**Comment by herpiko** [comment]
Moved to https://github.com/BlankOn/Verbeek/issues/59 since BlankOn distribution related stuff should be separated from irgsh development.
