### ISSUE TITLE
Can not add automatically user 'irgsh'

### ISSUE THREAD

**Issue by antosamalona** [BlankOn/irgsh-go#90]
When I exexuted this command, curl -L -o- https://raw.githubusercontent.com/BlankOn/irgsh-go/master/install.sh | bash 

It doesn't create user automatically

**Comment by herpiko** [comment]
@antosamalona Do you have more info about your environment? I mean the distribution name and version.

**Comment by samsulmaarif** [comment]
Already tested the script in Debian 10, i think it works fine.
