### ISSUE TITLE
Upload tarball first then post the metadata

### ISSUE THREAD

**Issue by herpiko** [BlankOn/irgsh-go#96]
https://github.com/BlankOn/irgsh-go/blob/master/cmd/cli/main.go#L238

0. Upload the tarball and get the uuid of the tarball
1. Post the metadata along with the tarball uuid

This is crucial since it's too silly to convert huge package like libreoffice suite to base64.
```
				jsonStr := "{ "
				jsonStr += "\"sourceUrl\":\"" + sourceUrl + "\", "
				jsonStr += "\"packageUrl\":\"" + packageUrl + "\", "
				jsonStr += "\"tarballUUID\": \"" + tarballUUID + "\", "  // <------ no longer including the base64 string.
				jsonStr += "\"isExperimental\": " + isExperimentalStr + " "
				jsonStr += "}"
```

**Comment by wejick** [comment]
iyes we need to change the file upload protocol / mechanism
